### ISSUE TITLE
Route::manage() 未定义

### ISSUE THREAD

**Issue by OliverGarfield** [duxphp/CMSRavel#1]
php artisan package:discover

   InvalidArgumentException 

  Attribute [manage] does not exist.

  at vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php:93
     89▕      */
     90▕     public function attribute($key, $value)
     91▕     {
     92▕         if (! in_array($key, $this->allowedAttributes)) {
  ➜  93▕             throw new InvalidArgumentException("Attribute [{$key}] does not exist.");
     94▕         }
     95▕ 
     96▕         $this->attributes[Arr::get($this->aliases, $key, $key)] = $value;
     97▕ 

      +2 vendor frames 
  3   modules/Article/Route/AuthAdmin.php:14
      Illuminate\Support\Facades\Facade::__callStatic()

      +3 vendor frames 
  7   modules/Article/Route/AuthAdmin.php:15
      Illuminate\Support\Facades\Facade::__callStatic()

**Comment by duxphp** [comment]
已解决
